runtime! config/**/*.vim

execute pathogen#infect()
execute pathogen#helptags()

set nocompatible
set laststatus=2
set t_Co=256
let g:airline_theme='simple'

if !exists('g:airline_symbols')
	  let g:airline_symbols = {}
  endif
  let g:airline_left_sep = ''
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ''
  let g:airline_right_alt_sep = ''
  let g:airline_symbols.branch = ''
  let g:airline_symbols.readonly = ''

filetype plugin indent on
syntax on


