runtime! config/**/*.vim

execute pathogen#infect()
execute pathogen#helptags()

set nocompatible
set laststatus=2
set t_Co=256
let g:airline_theme='simple'
let g:airline#extensions#tabline#enabled = 1

filetype plugin indent on
syntax on


